######################################################################
# Automatically generated by qmake (3.1) Thu Apr 28 23:02:07 2022
######################################################################

TEMPLATE = app
TARGET = example
INCLUDEPATH += . \
               ../CPP
LIBS += ../CPP/libbmp.a

DEFINES += QT_DEPRECATED_WARNINGS
QMAKE_CLEAN += $$TARGET

# Input
SOURCES += checkerboard.cpp
