######################################################################
# Automatically generated by qmake (3.1) Thu Apr 28 22:56:47 2022
######################################################################

TEMPLATE = lib
TARGET = bmp
INCLUDEPATH += .
CONFIG += staticlib 

DEFINES += QT_DEPRECATED_WARNINGS
QMAKE_CLEAN += $$TARGET

# Input
HEADERS += libbmp.h
SOURCES += libbmp.cpp
